### ISSUE TITLE
Incompatible with Docker Compose v2

### ISSUE THREAD

**Issue by Raniz85** [lando/core-next#46]
It seems Docker Compose 2.x names containers differently and this is causing Lando to not find them.

Docker Compose now uses `-` as a separator (see [here](https://github.com/docker/compose/pull/8655)) while Lando seems to be expecting `_` resulting in weird error messages when starting containers.

My setup continuously logs

> Waiting until database service is ready...

 Turning on verbose logging additionally shows 

> process pid37 had output stdout=, stderr=unknown shorthand flag: 'T' in -T`

Digging through the code with a debugger I discovered this error in `isRunning` in _docker.js_:

> Error: (HTTP code 404) no such container - No such container: XXX_database_1 
 
`docker ps` shows a running container named _XXX-database-1_.

**Comment by pirog** [comment]
@millnut FWIW i am running on 4.23.0 without issue. It might be worth noting that if you are on the most recent version of Lando it _should_ download and use Docker Compose 1 if it cannot find it in Docker Desktop and use that. It _should not_ use Docker Compose 2 unless you've explicitly configured it to do that.

**Comment by millnut** [comment]
Hi @pirog I'm using Lando v3.18.0. Docker Desktop had Docker Compose v2 set to disabled however the new version which I've just upgraded to has overridden that and seems to have forced Docker Compose v2 but they no longer have the ability to turn it off.

I wonder if upgrading to the next stable release of Lando will detect Docker Compose v1 is not there and download it.

**Comment by pirog** [comment]
@millnut this functionality was added in https://github.com/lando/core/releases/tag/v3.17.0 so youd need to have running that version of Lando core or higher

**Comment by millnut** [comment]
Thanks @pirog I forgot to mention I'm on macOS. I'm on 3.18 which is newer however I don't have a `~/.lando/bin` folder how can I force a generation of that folder to see if it resolves things

**Comment by pirog** [comment]
3.18 is the CLI version you are using, i am talking about the CORE version. You would need to update your CLI to https://github.com/lando/cli/releases/tag/v3.19.5 to get that version of CORE.

I understand the versioning between various components is currently confusing but it will be unified soonish.

**Comment by reynoldsalec** [comment]
Note that Lando is compatible with Docker Compose v2 as of v3.20, so this should no longer be an issue. See blog post for more details: https://lando.dev/blog/2023/09/25/v320-extended.html
